-- ---------------------------------------------------
-- TABLE CREATION
-- ---------------------------------------------------

CREATE TABLE tb_user (
	id_user UUID,
	name VARCHAR(120) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	role VARCHAR(80),
	id_kitchen INTEGER,
	id_profile INTEGER NOT NULL,
	active BOOLEAN NOT NULL DEFAULT true,
	last_login TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_user)
);

CREATE TABLE tb_profile (
	id_profile INTEGER GENERATED BY DEFAULT AS IDENTITY,
	access_type VARCHAR(50) NOT NULL UNIQUE,
	description VARCHAR(255),
	PRIMARY KEY (id_profile)
);

CREATE TABLE tb_kitchen (
	id_kitchen INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(120) NOT NULL,
	code VARCHAR(20) NOT NULL UNIQUE,
	address VARCHAR(255),
	active BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_kitchen)
);

CREATE TABLE tb_product (
	id_product INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(150) NOT NULL,
	brand VARCHAR(80),
	id_category INTEGER,
	id_unit INTEGER NOT NULL,
	barcode VARCHAR(50) UNIQUE,
	photo_url VARCHAR(255),
	active BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_product)
);

CREATE TABLE tb_category (
	id_category INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(80) NOT NULL UNIQUE,
	description VARCHAR(255),
	PRIMARY KEY (id_category)
);

CREATE TABLE tb_measurement_unit (
	id_unit INTEGER GENERATED BY DEFAULT AS IDENTITY,
	symbol VARCHAR(10) NOT NULL UNIQUE,
	description VARCHAR(60) NOT NULL,
	PRIMARY KEY (id_unit)
);

CREATE TABLE tb_product_supplier (
	id_product INTEGER NOT NULL,
	id_supplier INTEGER NOT NULL,
	supplier_code VARCHAR(50),
	reference_price DECIMAL(12,2),
	lead_time_days INTEGER,
	PRIMARY KEY (id_product, id_supplier)
);

CREATE TABLE tb_supplier (
	id_supplier INTEGER GENERATED BY DEFAULT AS IDENTITY,
	legal_name VARCHAR(150) NOT NULL,
	cnpj VARCHAR(18) NOT NULL UNIQUE,
	email VARCHAR(150),
	whatsapp VARCHAR(20),
	rating INTEGER,
	active BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_supplier)
);

CREATE TABLE tb_product_kitchen_parameter (
	id_product INTEGER NOT NULL,
	id_kitchen INTEGER NOT NULL,
	min_stock DECIMAL(12,3) NOT NULL DEFAULT 0,
	max_stock DECIMAL(12,3),
	average_daily_consumption DECIMAL(12,3),
	PRIMARY KEY (id_product, id_kitchen)
);

CREATE TABLE tb_stock_batch (
	id_batch INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_product INTEGER NOT NULL,
	id_kitchen INTEGER NOT NULL,
	id_supplier INTEGER,
	batch_number VARCHAR(50) NOT NULL,
	invoice_number VARCHAR(50),
	initial_quantity DECIMAL(12,3) NOT NULL,
	current_quantity DECIMAL(12,3) NOT NULL,
	entry_date DATE NOT NULL,
	expiration_date DATE,
	unit_price DECIMAL(12,2),
	status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	PRIMARY KEY (id_batch)
);

CREATE TABLE tb_requisition (
	id_requisition INTEGER GENERATED BY DEFAULT AS IDENTITY,
	requisition_type VARCHAR(20) NOT NULL,
	origin VARCHAR(20) NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'UNDER_REVIEW',
	reason VARCHAR(255),
	id_kitchen INTEGER NOT NULL,
	id_requester_user UUID NOT NULL,
	id_approver_user UUID,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	approved_at TIMESTAMP,
	PRIMARY KEY (id_requisition)
);

CREATE TABLE tb_requisition_item (
	id_requisition_item INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_requisition INTEGER NOT NULL,
	id_product INTEGER NOT NULL,
	id_suggested_supplier INTEGER,
	quantity DECIMAL(12,3) NOT NULL,
	estimated_price DECIMAL(12,2),
	note VARCHAR(255),
	PRIMARY KEY (id_requisition_item)
);

CREATE TABLE tb_inventory (
	id_inventory INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_kitchen INTEGER NOT NULL,
	id_responsible_user UUID NOT NULL,
	started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	closed_at TIMESTAMP,
	status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
	note VARCHAR(255),
	PRIMARY KEY (id_inventory)
);

CREATE TABLE tb_inventory_count (
	id_count INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_inventory INTEGER NOT NULL,
	id_batch INTEGER NOT NULL,
	registered_quantity DECIMAL(12,3) NOT NULL,
	physical_quantity DECIMAL(12,3) NOT NULL,
	divergence DECIMAL(12,3),
	note VARCHAR(255),
	PRIMARY KEY (id_count)
);

CREATE TABLE tb_alert (
	id_alert INTEGER GENERATED BY DEFAULT AS IDENTITY,
	type VARCHAR(30) NOT NULL,
	severity VARCHAR(10) NOT NULL,
	id_batch INTEGER,
	id_product INTEGER,
	id_kitchen INTEGER NOT NULL,
	message VARCHAR(255) NOT NULL,
	is_read BOOLEAN NOT NULL DEFAULT false,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_alert)
);