-- ---------------------------------------------------
-- LOG TABLE CREATION
-- ---------------------------------------------------

CREATE TABLE tb_log_user (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_user UUID,
    operation VARCHAR(10) NOT NULL,
    db_user VARCHAR(100) NOT NULL,
    operation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    previous_data JSONB,
    new_data JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_product (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_product INTEGER,
    operation VARCHAR(10) NOT NULL,
    db_user VARCHAR(100) NOT NULL,
    operation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    previous_data JSONB,
    new_data JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_supplier (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_supplier INTEGER,
    operation VARCHAR(10) NOT NULL,
    db_user VARCHAR(100) NOT NULL,
    operation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    previous_data JSONB,
    new_data JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_stock_batch (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_batch INTEGER,
    operation VARCHAR(10) NOT NULL,
    db_user VARCHAR(100) NOT NULL,
    operation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    previous_data JSONB,
    new_data JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_requisition (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_requisition INTEGER,
    operation VARCHAR(10) NOT NULL,
    db_user VARCHAR(100) NOT NULL,
    operation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    previous_data JSONB,
    new_data JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_inventory (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_inventory INTEGER,
    operation VARCHAR(10) NOT NULL,
    db_user VARCHAR(100) NOT NULL,
    operation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    previous_data JSONB,
    new_data JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_alert (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_alert INTEGER,
    operation VARCHAR(10) NOT NULL,
    db_user VARCHAR(100) NOT NULL,
    operation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    previous_data JSONB,
    new_data JSONB,
    PRIMARY KEY (id_log)
);