-- ---------------------------------------------------
-- CRIAÇÃO DAS TABELAS DE LOG
-- ---------------------------------------------------

CREATE TABLE tb_log_usuario (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario UUID,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_produto (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_produto INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_fornecedor (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_fornecedor INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_estoque_lote (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_lote INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_requisicao (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_requisicao INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_inventario (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_inventario INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE tb_log_alerta (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_alerta INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);