-- ---------------------------------------------------
-- CRIAÇÃO DAS TABELAS
-- ---------------------------------------------------

CREATE TABLE IF NOT EXISTS tb_usuario (
	id_usuario UUID,
	nome VARCHAR(120) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	senha_hash VARCHAR(255) NOT NULL,
	cargo VARCHAR(80),
	id_cozinha INTEGER,
	id_perfil INTEGER NOT NULL,
	ativo BOOLEAN NOT NULL DEFAULT true,
	ultimo_login TIMESTAMP,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_usuario)
);

CREATE TABLE IF NOT EXISTS tb_perfil (
	id_perfil INTEGER GENERATED BY DEFAULT AS IDENTITY,
	tipo_acesso VARCHAR(50) NOT NULL UNIQUE,
	descricao VARCHAR(255),
	PRIMARY KEY (id_perfil)
);

CREATE TABLE IF NOT EXISTS tb_cozinha (
	id_cozinha INTEGER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(120) NOT NULL,
	codigo VARCHAR(20) NOT NULL UNIQUE,
	endereco VARCHAR(255),
	ativo BOOLEAN NOT NULL DEFAULT true,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_cozinha)
);

CREATE TABLE IF NOT EXISTS tb_produto (
	id_produto INTEGER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(150) NOT NULL,
	marca VARCHAR(80),
	id_categoria INTEGER,
	id_unidade INTEGER NOT NULL,
	codigo_barras VARCHAR(50) UNIQUE,
	foto_url VARCHAR(255),
	ativo BOOLEAN NOT NULL DEFAULT true,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_produto)
);

CREATE TABLE IF NOT EXISTS tb_categoria (
	id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(80) NOT NULL UNIQUE,
	descricao VARCHAR(255),
	PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS tb_unidade_medida (
	id_unidade INTEGER GENERATED BY DEFAULT AS IDENTITY,
	sigla VARCHAR(10) NOT NULL UNIQUE,
	descricao VARCHAR(60) NOT NULL,
	PRIMARY KEY (id_unidade)
);

CREATE TABLE IF NOT EXISTS tb_produto_fornecedor (
	id_produto INTEGER NOT NULL,
	id_fornecedor INTEGER NOT NULL,
	codigo_no_fornecedor VARCHAR(50),
	preco_referencia DECIMAL(12,2),
	lead_time_dias INTEGER,
	PRIMARY KEY (id_produto, id_fornecedor)
);

CREATE TABLE IF NOT EXISTS tb_fornecedor (
	id_fornecedor INTEGER GENERATED BY DEFAULT AS IDENTITY,
	nome_juridico VARCHAR(150) NOT NULL,
	cnpj VARCHAR(18) NOT NULL UNIQUE,
	email VARCHAR(150),
	whatsapp VARCHAR(20),
	nota_avaliacao INTEGER,
	ativo BOOLEAN NOT NULL DEFAULT true,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_fornecedor)
);

CREATE TABLE IF NOT EXISTS tb_produto_parametro_cozinha (
	id_produto INTEGER NOT NULL,
	id_cozinha INTEGER NOT NULL,
	estoque_minimo DECIMAL(12,3) NOT NULL DEFAULT 0,
	estoque_maximo DECIMAL(12,3),
	consumo_medio_dia DECIMAL(12,3),
	PRIMARY KEY (id_produto, id_cozinha)
);

CREATE TABLE IF NOT EXISTS tb_estoque_lote (
	id_lote INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_produto INTEGER NOT NULL,
	id_cozinha INTEGER NOT NULL,
	id_fornecedor INTEGER,
	numero_lote VARCHAR(50) NOT NULL,
	numero_nota_fiscal VARCHAR(50),
	qtd_inicial DECIMAL(12,3) NOT NULL,
	qtd_atual DECIMAL(12,3) NOT NULL,
	data_entrada DATE NOT NULL,
	data_validade DATE,
	preco_unitario DECIMAL(12,2),
	status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
	PRIMARY KEY (id_lote)
);

CREATE TABLE IF NOT EXISTS tb_requisicao (
	id_requisicao INTEGER GENERATED BY DEFAULT AS IDENTITY,
	tipo_requisicao VARCHAR(20) NOT NULL,
	origem VARCHAR(20) NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'EM_ANALISE',
	motivo VARCHAR(255),
	id_cozinha INTEGER NOT NULL,
	id_usuario_requisicao UUID NOT NULL,
	id_usuario_aprovador UUID,
	data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	data_aprovacao TIMESTAMP,
	PRIMARY KEY (id_requisicao)
);

CREATE TABLE IF NOT EXISTS tb_requisicao_item (
	id_requisicao_item INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_requisicao INTEGER NOT NULL,
	id_produto INTEGER NOT NULL,
	id_fornecedor_sugerido INTEGER,
	quantidade DECIMAL(12,3) NOT NULL,
	preco_estimado DECIMAL(12,2),
	observacao VARCHAR(255),
	PRIMARY KEY (id_requisicao_item)
);

CREATE TABLE IF NOT EXISTS tb_inventario (
	id_inventario INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_cozinha INTEGER NOT NULL,
	id_usuario_responsavel UUID NOT NULL,
	data_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	data_fechamento TIMESTAMP,
	status VARCHAR(20) NOT NULL DEFAULT 'ABERTO',
	observacao VARCHAR(255),
	PRIMARY KEY (id_inventario)
);

CREATE TABLE IF NOT EXISTS tb_inventario_contagem (
	id_contagem INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_inventario INTEGER NOT NULL,
	id_lote INTEGER NOT NULL,
	qtd_registrada DECIMAL(12,3) NOT NULL,
	qtd_fisica DECIMAL(12,3) NOT NULL,
	divergencia DECIMAL(12,3),
	observacao VARCHAR(255),
	PRIMARY KEY (id_contagem)
);

CREATE TABLE IF NOT EXISTS tb_alerta (
	id_alerta INTEGER GENERATED BY DEFAULT AS IDENTITY,
	tipo VARCHAR(30) NOT NULL,
	severidade VARCHAR(10) NOT NULL,
	id_lote INTEGER,
	id_produto INTEGER,
	id_cozinha INTEGER NOT NULL,
	mensagem VARCHAR(255) NOT NULL,
	lido BOOLEAN NOT NULL DEFAULT false,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_alerta)
);


-- ---------------------------------------------------
-- CRIAÇÃO DE CHAVES ESTRANGEIRAS
-- ---------------------------------------------------

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_usuario_perfil') THEN	
		ALTER TABLE tb_usuario
		ADD CONSTRAINT fk_usuario_perfil
		FOREIGN KEY (id_perfil) REFERENCES tb_perfil (id_perfil)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_usuario_cozinha') THEN
		ALTER TABLE tb_usuario
		ADD CONSTRAINT fk_usuario_cozinha
		FOREIGN KEY (id_cozinha) REFERENCES tb_cozinha (id_cozinha)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_produto_categoria') THEN
		ALTER TABLE tb_produto
		ADD CONSTRAINT fk_produto_categoria
		FOREIGN KEY (id_categoria) REFERENCES tb_categoria (id_categoria)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_produto_unidade') THEN
		ALTER TABLE tb_produto
		ADD CONSTRAINT fk_produto_unidade
		FOREIGN KEY (id_unidade) REFERENCES tb_unidade_medida (id_unidade)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_produtofornecedor_produto') THEN
		ALTER TABLE tb_produto_fornecedor
		ADD CONSTRAINT fk_produtofornecedor_produto
		FOREIGN KEY (id_produto) REFERENCES tb_produto (id_produto)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_produtofornecedor_fornecedor') THEN
		ALTER TABLE tb_produto_fornecedor
		ADD CONSTRAINT fk_produtofornecedor_fornecedor
		FOREIGN KEY (id_fornecedor) REFERENCES tb_fornecedor (id_fornecedor)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_parametro_produto') THEN
		ALTER TABLE tb_produto_parametro_cozinha
		ADD CONSTRAINT fk_parametro_produto
		FOREIGN KEY (id_produto) REFERENCES tb_produto (id_produto)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_parametro_cozinha') THEN
		ALTER TABLE tb_produto_parametro_cozinha
		ADD CONSTRAINT fk_parametro_cozinha
		FOREIGN KEY (id_cozinha) REFERENCES tb_cozinha (id_cozinha)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lote_produto') THEN
		ALTER TABLE tb_estoque_lote
		ADD CONSTRAINT fk_lote_produto
		FOREIGN KEY (id_produto) REFERENCES tb_produto (id_produto)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lote_cozinha') THEN
		ALTER TABLE tb_estoque_lote
		ADD CONSTRAINT fk_lote_cozinha
		FOREIGN KEY (id_cozinha) REFERENCES tb_cozinha (id_cozinha)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lote_fornecedor') THEN
		ALTER TABLE tb_estoque_lote
		ADD CONSTRAINT fk_lote_fornecedor
		FOREIGN KEY (id_fornecedor) REFERENCES tb_fornecedor (id_fornecedor)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisicao_cozinha') THEN
		ALTER TABLE tb_requisicao
		ADD CONSTRAINT fk_requisicao_cozinha
		FOREIGN KEY (id_cozinha) REFERENCES tb_cozinha (id_cozinha)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisicao_usuario_solicitante') THEN
		ALTER TABLE tb_requisicao
		ADD CONSTRAINT fk_requisicao_usuario_solicitante
		FOREIGN KEY (id_usuario_requisicao) REFERENCES tb_usuario (id_usuario)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisicao_usuario_aprovador') THEN
		ALTER TABLE tb_requisicao
		ADD CONSTRAINT fk_requisicao_usuario_aprovador
		FOREIGN KEY (id_usuario_aprovador) REFERENCES tb_usuario (id_usuario)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisicaoitem_requisicao') THEN
		ALTER TABLE tb_requisicao_item
		ADD CONSTRAINT fk_requisicaoitem_requisicao
		FOREIGN KEY (id_requisicao) REFERENCES tb_requisicao (id_requisicao)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisicaoitem_produto') THEN
		ALTER TABLE tb_requisicao_item
		ADD CONSTRAINT fk_requisicaoitem_produto
		FOREIGN KEY (id_produto) REFERENCES tb_produto (id_produto)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisicaoitem_fornecedor') THEN
		ALTER TABLE tb_requisicao_item
		ADD CONSTRAINT fk_requisicaoitem_fornecedor
		FOREIGN KEY (id_fornecedor_sugerido) REFERENCES tb_fornecedor (id_fornecedor)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_inventario_cozinha') THEN
		ALTER TABLE tb_inventario
		ADD CONSTRAINT fk_inventario_cozinha
		FOREIGN KEY (id_cozinha) REFERENCES tb_cozinha (id_cozinha)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_inventario_usuario') THEN
		ALTER TABLE tb_inventario
		ADD CONSTRAINT fk_inventario_usuario
		FOREIGN KEY (id_usuario_responsavel) REFERENCES tb_usuario (id_usuario)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contagem_inventario') THEN
		ALTER TABLE tb_inventario_contagem
		ADD CONSTRAINT fk_contagem_inventario
		FOREIGN KEY (id_inventario) REFERENCES tb_inventario (id_inventario)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contagem_lote') THEN
		ALTER TABLE tb_inventario_contagem
		ADD CONSTRAINT fk_contagem_lote
		FOREIGN KEY (id_lote) REFERENCES tb_estoque_lote (id_lote)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alerta_cozinha') THEN
		ALTER TABLE tb_alerta
		ADD CONSTRAINT fk_alerta_cozinha
		FOREIGN KEY (id_cozinha) REFERENCES tb_cozinha (id_cozinha)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alerta_produto') THEN
		ALTER TABLE tb_alerta
		ADD CONSTRAINT fk_alerta_produto
		FOREIGN KEY (id_produto) REFERENCES tb_produto (id_produto)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alerta_lote') THEN
		ALTER TABLE tb_alerta
		ADD CONSTRAINT fk_alerta_lote
		FOREIGN KEY (id_lote) REFERENCES tb_estoque_lote (id_lote)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;		
$$;

-- ---------------------------------------------------
-- CRIAÇÃO DE CONSTRAINTS DE CHECK 
-- ---------------------------------------------------

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_fornecedor_nota') THEN
		ALTER TABLE tb_fornecedor
		ADD CONSTRAINT ck_fornecedor_nota 
		CHECK (nota_avaliacao BETWEEN 1 AND 5);
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_lote_status') THEN
		ALTER TABLE tb_estoque_lote
		ADD CONSTRAINT ck_lote_status 
		CHECK (status IN ('ATIVO', 'BAIXA', 'VENCIDO', 'CANCELADO'));
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_requisicao_status') THEN
		ALTER TABLE tb_requisicao
		ADD CONSTRAINT ck_requisicao_status 
		CHECK (status IN ('EM_ANALISE', 'APROVADO', 'REPROVADO', 'CANCELADO'));
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_requisicao_tipo') THEN
		ALTER TABLE tb_requisicao
		ADD CONSTRAINT ck_requisicao_tipo 
		CHECK (tipo_requisicao IN ('COMPRA', 'TRANSFERENCIA', 'CONSUMO'));
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_inventario_status') THEN
		ALTER TABLE tb_inventario
		ADD CONSTRAINT ck_inventario_status 
		CHECK (status IN ('ABERTO', 'FECHADO', 'CANCELADO'));
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_alerta_severidade') THEN
		ALTER TABLE tb_alerta
		ADD CONSTRAINT ck_alerta_severidade 
		CHECK (severidade IN ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA'));
	END IF;
END;
$$;		

-- ---------------------------------------------------
-- CRIAÇÃO DE ÍNDICES
-- ---------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_usuario_perfil 
ON tb_usuario (id_perfil);

CREATE INDEX IF NOT EXISTS idx_usuario_cozinha 
ON tb_usuario (id_cozinha);

CREATE INDEX IF NOT EXISTS idx_usuario_email 
ON tb_usuario (email);

CREATE INDEX IF NOT EXISTS idx_usuario_ativo 
ON tb_usuario (ativo);

CREATE INDEX IF NOT EXISTS idx_produto_categoria 
ON tb_produto (id_categoria);

CREATE INDEX IF NOT EXISTS idx_produto_unidade 
ON tb_produto (id_unidade);

CREATE INDEX IF NOT EXISTS idx_produto_codigo_barras 
ON tb_produto (codigo_barras);

CREATE INDEX IF NOT EXISTS idx_produto_ativo 
ON tb_produto (ativo);

CREATE INDEX IF NOT EXISTS idx_produtofornecedor_produto 
ON tb_produto_fornecedor (id_produto);

CREATE INDEX IF NOT EXISTS idx_produtofornecedor_fornecedor 
ON tb_produto_fornecedor (id_fornecedor);

CREATE INDEX IF NOT EXISTS idx_parametro_produto 
ON tb_produto_parametro_cozinha (id_produto);

CREATE INDEX IF NOT EXISTS idx_parametro_cozinha 
ON tb_produto_parametro_cozinha (id_cozinha);

CREATE INDEX IF NOT EXISTS idx_lote_produto 
ON tb_estoque_lote (id_produto);

CREATE INDEX IF NOT EXISTS idx_lote_cozinha 
ON tb_estoque_lote (id_cozinha);

CREATE INDEX IF NOT EXISTS idx_lote_fornecedor 
ON tb_estoque_lote (id_fornecedor);

CREATE INDEX IF NOT EXISTS idx_lote_status 
ON tb_estoque_lote (status);

CREATE INDEX IF NOT EXISTS idx_lote_data_validade 
ON tb_estoque_lote (data_validade);

CREATE INDEX IF NOT EXISTS idx_requisicao_cozinha 
ON tb_requisicao (id_cozinha);

CREATE INDEX IF NOT EXISTS idx_requisicao_usuario_solicitante 
ON tb_requisicao (id_usuario_requisicao);

CREATE INDEX IF NOT EXISTS idx_requisicao_usuario_aprovador 
ON tb_requisicao (id_usuario_aprovador);

CREATE INDEX IF NOT EXISTS idx_requisicao_status 
ON tb_requisicao (status);

CREATE INDEX IF NOT EXISTS idx_requisicao_data_hora 
ON tb_requisicao (data_hora);

CREATE INDEX IF NOT EXISTS idx_requisicaoitem_requisicao 
ON tb_requisicao_item (id_requisicao);

CREATE INDEX IF NOT EXISTS idx_requisicaoitem_produto 
ON tb_requisicao_item (id_produto);

CREATE INDEX IF NOT EXISTS idx_requisicaoitem_fornecedor 
ON tb_requisicao_item (id_fornecedor_sugerido);

CREATE INDEX IF NOT EXISTS idx_inventario_cozinha 
ON tb_inventario (id_cozinha);

CREATE INDEX IF NOT EXISTS idx_inventario_usuario 
ON tb_inventario (id_usuario_responsavel);

CREATE INDEX IF NOT EXISTS idx_inventario_status 
ON tb_inventario (status);

CREATE INDEX IF NOT EXISTS idx_contagem_inventario 
ON tb_inventario_contagem (id_inventario);

CREATE INDEX IF NOT EXISTS idx_contagem_lote 
ON tb_inventario_contagem (id_lote);

CREATE INDEX IF NOT EXISTS idx_alerta_cozinha 
ON tb_alerta (id_cozinha);

CREATE INDEX IF NOT EXISTS idx_alerta_produto 
ON tb_alerta (id_produto);

CREATE INDEX IF NOT EXISTS idx_alerta_lote 
ON tb_alerta (id_lote);

CREATE INDEX IF NOT EXISTS idx_alerta_lido 
ON tb_alerta (lido);

CREATE INDEX IF NOT EXISTS idx_alerta_severidade 
ON tb_alerta (severidade);

CREATE INDEX IF NOT EXISTS idx_alerta_criado_em 
ON tb_alerta (criado_em);