-- ---------------------------------------------------
-- CRIAÇÃO DAS TABELAS DE LOG
-- ---------------------------------------------------

CREATE TABLE IF NOT EXISTS tb_log_usuario (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario UUID,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE IF NOT EXISTS tb_log_produto (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_produto INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE IF NOT EXISTS tb_log_fornecedor (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_fornecedor INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE IF NOT EXISTS tb_log_estoque_lote (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_lote INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE IF NOT EXISTS tb_log_requisicao (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_requisicao INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE IF NOT EXISTS tb_log_inventario (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_inventario INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

CREATE TABLE IF NOT EXISTS tb_log_alerta (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_alerta INTEGER,
    operacao VARCHAR(10) NOT NULL,
    usuario_bd VARCHAR(100) NOT NULL,
    data_operacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores JSONB,
    dados_novos JSONB,
    PRIMARY KEY (id_log)
);

-- ---------------------------------------------------
-- CRIAÇÃO DE FUNCTIONS DE LOG
-- ---------------------------------------------------

CREATE OR REPLACE FUNCTION fn_log_usuario()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO tb_log_usuario
        (id_usuario, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_usuario, TG_OP, CURRENT_USER, NULL, to_jsonb(NEW));

        RETURN NEW;  

    ELSIF TG_OP = 'UPDATE' THEN

        INSERT INTO tb_log_usuario
        (id_usuario, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_usuario, TG_OP, CURRENT_USER, to_jsonb(OLD), to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN

        INSERT INTO tb_log_usuario
        (id_usuario, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (OLD.id_usuario, TG_OP, CURRENT_USER, to_jsonb(OLD), NULL);

        RETURN OLD;

    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION fn_log_produto()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF TG_OP = 'INSERT' THEN

        INSERT INTO tb_log_produto
        (id_produto, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_produto, TG_OP, CURRENT_USER, NULL, to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN

        INSERT INTO tb_log_produto
        (id_produto, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_produto, TG_OP, CURRENT_USER, to_jsonb(OLD), to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN

        INSERT INTO tb_log_produto
        (id_produto, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (OLD.id_produto, TG_OP, CURRENT_USER, to_jsonb(OLD), NULL);

        RETURN OLD;

    END IF;
END;
$$;


CREATE OR REPLACE FUNCTION fn_log_fornecedor()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF TG_OP = 'INSERT' THEN

        INSERT INTO tb_log_fornecedor
        (id_fornecedor, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_fornecedor, TG_OP, CURRENT_USER, NULL, to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN

        INSERT INTO tb_log_fornecedor
        (id_fornecedor, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_fornecedor, TG_OP, CURRENT_USER, to_jsonb(OLD), to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN

        INSERT INTO tb_log_fornecedor
        (id_fornecedor, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (OLD.id_fornecedor, TG_OP, CURRENT_USER, to_jsonb(OLD), NULL);

        RETURN OLD;

    END IF;
END;
$$;


CREATE OR REPLACE FUNCTION fn_log_estoque_lote()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF TG_OP = 'INSERT' THEN

        INSERT INTO tb_log_estoque_lote
        (id_lote, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_lote, TG_OP, CURRENT_USER, NULL, to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN

        INSERT INTO tb_log_estoque_lote
        (id_lote, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_lote, TG_OP, CURRENT_USER, to_jsonb(OLD), to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN

        INSERT INTO tb_log_estoque_lote
        (id_lote, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (OLD.id_lote, TG_OP, CURRENT_USER, to_jsonb(OLD), NULL);

        RETURN OLD;

    END IF;
END;
$$;


CREATE OR REPLACE FUNCTION fn_log_requisicao()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF TG_OP = 'INSERT' THEN

        INSERT INTO tb_log_requisicao
        (id_requisicao, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_requisicao, TG_OP, CURRENT_USER, NULL, to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN

        INSERT INTO tb_log_requisicao
        (id_requisicao, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_requisicao, TG_OP, CURRENT_USER, to_jsonb(OLD), to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN

        INSERT INTO tb_log_requisicao
        (id_requisicao, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (OLD.id_requisicao, TG_OP, CURRENT_USER, to_jsonb(OLD), NULL);

        RETURN OLD;

    END IF;
END;
$$;


CREATE OR REPLACE FUNCTION fn_log_inventario()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF TG_OP = 'INSERT' THEN

        INSERT INTO tb_log_inventario
        (id_inventario, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_inventario, TG_OP, CURRENT_USER, NULL, to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN

        INSERT INTO tb_log_inventario
        (id_inventario, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_inventario, TG_OP, CURRENT_USER, to_jsonb(OLD), to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN

        INSERT INTO tb_log_inventario
        (id_inventario, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (OLD.id_inventario, TG_OP, CURRENT_USER, to_jsonb(OLD), NULL);

        RETURN OLD;

    END IF;
END;
$$;


CREATE OR REPLACE FUNCTION fn_log_alerta()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF TG_OP = 'INSERT' THEN

        INSERT INTO tb_log_alerta
        (id_alerta, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_alerta, TG_OP, CURRENT_USER, NULL, to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN

        INSERT INTO tb_log_alerta
        (id_alerta, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (NEW.id_alerta, TG_OP, CURRENT_USER, to_jsonb(OLD), to_jsonb(NEW));

        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN

        INSERT INTO tb_log_alerta
        (id_alerta, operacao, usuario_bd, dados_anteriores, dados_novos)
        VALUES
        (OLD.id_alerta, TG_OP, CURRENT_USER, to_jsonb(OLD), NULL);

        RETURN OLD;

    END IF;
END;
$$;

-- ---------------------------------------------------
-- CRIAÇÃO DE TRIGGERS DE LOG
-- ---------------------------------------------------

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_log_usuario') THEN
        CREATE TRIGGER trg_log_usuario
        AFTER INSERT OR UPDATE OR DELETE
        ON tb_usuario
        FOR EACH ROW EXECUTE FUNCTION fn_log_usuario();
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_log_produto') THEN
        CREATE TRIGGER trg_log_produto
        AFTER INSERT OR UPDATE OR DELETE
        ON tb_produto
        FOR EACH ROW EXECUTE FUNCTION fn_log_produto();
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_log_fornecedor') THEN
        CREATE TRIGGER trg_log_fornecedor
        AFTER INSERT OR UPDATE OR DELETE
        ON tb_fornecedor
        FOR EACH ROW EXECUTE FUNCTION fn_log_fornecedor();
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_log_estoque_lote') THEN
        CREATE TRIGGER trg_log_estoque_lote
        AFTER INSERT OR UPDATE OR DELETE
        ON tb_estoque_lote
        FOR EACH ROW EXECUTE FUNCTION fn_log_estoque_lote();
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_log_requisicao') THEN
        CREATE TRIGGER trg_log_requisicao
        AFTER INSERT OR UPDATE OR DELETE
        ON tb_requisicao
        FOR EACH ROW EXECUTE FUNCTION fn_log_requisicao();
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_log_inventario') THEN
        CREATE TRIGGER trg_log_inventario
        AFTER INSERT OR UPDATE OR DELETE
        ON tb_inventario
        FOR EACH ROW EXECUTE FUNCTION fn_log_inventario();
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_log_alerta') THEN
        CREATE TRIGGER trg_log_alerta
        AFTER INSERT OR UPDATE OR DELETE
        ON tb_alerta
        FOR EACH ROW EXECUTE FUNCTION fn_log_alerta();
    END IF;
END;
$$;